### ISSUE TITLE
Output OF vectors instead of colour wheel (flow_viz)

### ISSUE THREAD

**Issue by TranNg65** [hmorimitsu/ptlflow#42]
Hi hmorimitsu,

This is not an issue but I'm not sure where to ask this question. Please feel free to move this thread if required.

I'm trying to get a dense flow map with vectors- an array that has the same size with the image that contains (x,y) displacement at each pixel.

Can you please help me with some hints? I'm using RAFT_s model

Thanks again for your great work.

**Comment by hmorimitsu** [comment]
Hi,

I'm not sure if I understand what your problem is, but I think what you want is to run an inference with an optical flow model.

You can check examples of how to get the optical flow (dense flow map) in the documentation:

https://ptlflow.readthedocs.io/en/latest/starting/inference.html

or in this example in Google Colab:

https://colab.research.google.com/drive/1YARBRUGplqTRnRuY9sKIs6LY_2kWAWZJ?usp=sharing

I hope that helps.

**Comment by TranNg65** [comment]
Hi hmorimitsu,

Thank you very much for your reply. I have been looking at your recommendations

What I meant was how to get the dense flow map in vectors instead of colours. I'm using a RAFT model, does the vectors values of the whole images is the parameter **flow_up**?

https://github.com/hmorimitsu/ptlflow/blob/d5ec04e01c20e7680ff97f3bad5e57da9185034d/ptlflow/models/raft/raft.py#L164

Once again. Thank you.

**Comment by TranNg65** [comment]
Thank you very much.
